#jc19 258
saritasa-nest/camp-js-2022-daniil-koh pull request #1
Opened 2022-01-31 07:19 UTC by Danissimo-k

Authorization and table

2022-02-04 02:34 UTC, pavel-romanov8 requested changes

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Auth/AuthModal.ts
> +      const authForm: Element = (<Element> TEMPLATE_EL.querySelector('.auth-form'));
`querySelector` has a generic where you can specify element type f.e. `TEMPLATE_EL.querySelector<HTMLButtonElement>(.button)`

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Auth/AuthModal.ts
> +      // @ts-ignore
Because of poor typing and type checking, you have to use `@ts-ignore`. But it doesn't make any sense to use typescript if you disable it. At least prefer type assertion

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Auth/AuthModal.ts
> +      await signIn(emailElement.value, passwordElement.value).then(() => render());
Don't mix 2 approaches to work with promises. Choose `async/await` or `then` and stick to it everywhere. It makes your code consistent and helps to avoid errors.

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Auth/AuthModal.ts
> +  function getElement(): Element {
Again, poor typing. Please improve it. `Element` is too general type. You can use `HTMLDivElement` instead.

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/DTO/filmDTO.ts
> +export interface FilmDTO {
Don't forget to disable linter rules for the DTO files.

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/DTO/filmDTO.ts
> +  characters: number[];
Make fields of the DTO read-only

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/DTO/peopleDTO.ts
> +  birthYear: string;
It is strange that one of the DTOs has snake-case files and this one camelCase. Is it like that in firebase as well?

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Navbar/Navbar.ts
> +  <ul class="right hide-on-med-and-down">
Please, format it properly because it looks kinda odd

2022-02-04 02:34 UTC, pavel-romanov8 commented on vanila/src/Table/Table.ts
> +// const sortingKeys = ["title", "director", "producer", 'release_date'];
Remove dead code, please

2022-02-04 06:35 UTC, elena-dragunova requested changes

2022-02-04 06:35 UTC, elena-dragunova commented on vanila/src/Navbar/Navbar.ts
> +<div class="container-fluid" style="margin:0px 30px;">
Avoid inline styles, please: https://frontendwiki.saritasa.rocks/pages/development/languages/css.html#avoid-inline-styles

2022-02-04 06:35 UTC, elena-dragunova commented on vanila/src/Navbar/Navbar.ts
> +<li><a href="">Log ing</a></li>
It's a typo I guess

2022-02-04 06:35 UTC, elena-dragunova commented on vanila/src/index.css
> +  color: gray;
Use variables for colors, please.

2022-02-04 06:44 UTC, golovachev-yaroslav requested changes

2022-02-04 06:44 UTC, golovachev-yaroslav commented on vanila/src/Navbar/Navbar.ts
> +<a href="" class="brand-logo left">Logo</a>
Usually logo link goes to the home page, in this case `href="/"`

2022-02-04 06:44 UTC, golovachev-yaroslav commented on vanila/src/Navbar/Navbar.ts
> +  <a href="" class="button-collapse right" data-activates="sidenav">MENU</a>
Not symantec tag, please use button tag.

2022-02-04 06:44 UTC, golovachev-yaroslav commented on vanila/src/Navbar/Navbar.ts
> +<li><a href="">Log ing</a></li>
Looks like it should be a button.

2022-02-04 06:44 UTC, golovachev-yaroslav commented on vanila/src/index.css
> +  border: 1px solid #EEEEEE;
- Usually, we set color values in lower case. 
- Please move it to a var
- You can reduce value to` #eee`

2022-02-04 06:44 UTC, golovachev-yaroslav commented on vanila/src/index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Is it possible move it before closing body tag?

2022-02-05 05:19 UTC, Danissimo-k commented on vanila/src/middlewares/getFormattedCollectionData.ts
> +  docSnap.forEach(document => {
I tried it but method map is undefined for QuerySnapshot.

2022-02-07 03:40 UTC, golovachev-yaroslav approved these changes

2022-02-07 03:51 UTC, panov-aleksey-saritasa approved these changes

2022-02-07 03:51 UTC, panov-aleksey-saritasa commented on vanila/src/Interfaces/authFormElements.ts
> +export interface authFormElements extends HTMLCollection {
Please, don't forget to check linter warnings/errors

2022-02-07 03:51 UTC, panov-aleksey-saritasa commented on vanila/src/Table/Table.ts
> +    const films = <CollectionDTO<FilmDTO>[]>data;
`<CollectionDTO<FilmDTO>[]>` type casting is unnecessary here

2022-02-07 03:51 UTC, panov-aleksey-saritasa commented on vanila/src/middlewares/getFormattedCollectionData.ts
> +  const docSnap: QuerySnapshot<DocumentData> = await func();
Please, always stick to one approach when working with Promises throughout your application. Either `async/await` or `then/catch`

2022-02-07 03:51 UTC, panov-aleksey-saritasa commented on vanila/src/middlewares/getFormattedCollectionData.ts
> +  docSnap.forEach(document => {
Maybe `docSnap.docs.map(...)` is what you need

2022-02-07 03:52 UTC, panov-aleksey-saritasa commented
FYI, If you are done fixing your issues you can re-request review
![image](https://user-images.githubusercontent.com/86595878/152721898-8269c787-b241-478e-8f7c-033d857e9dc3.png)

2022-02-07 07:37 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-02-07 14:26 UTC, timofei-maximov-saritasa commented on vanila/src/DTO/filmDTO.ts
> +  readonly vehicles: number[];
Please, add `readonly` for arrays

2022-02-07 14:26 UTC, timofei-maximov-saritasa commented on vanila/src/Table/Table.ts
> +      const titleEL: HTMLTableCellElement = document.createElement('td');
Please, [avoid contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-07 14:26 UTC, timofei-maximov-saritasa commented on vanila/src/Interfaces/authFormElements.ts
> +  emailElement: HTMLInputElement;
Do not forget to add `readonly` [wiki](https://frontendwiki.saritasa.rocks/pages/development/languages/typescript.html#promote-immutability)

2022-02-07 14:28 UTC, timofei-maximov-saritasa approved these changes

2022-02-07 15:08 UTC, Danissimo-k commented on vanila/src/Table/Table.ts
> +      const titleEL: HTMLTableCellElement = document.createElement('td');
I need to do that cause a had dto fields names as 'director', 'release_date', 'producer', 'title'. I can change name as example: "directorArea" but i think it is odd

2022-02-08 01:48 UTC, dbitkovski approved these changes

2022-02-08 04:47 UTC, elena-dragunova approved these changes

2022-02-08 08:21 UTC, merged