#jc19 258 detail page
saritasa-nest/camp-js-2022-daniil-koh pull request #2
Opened 2022-02-15 02:17 UTC by Danissimo-k

Detail page of all film fields info.

2022-02-15 04:23 UTC, golovachev-yaroslav requested changes

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Auth/AuthModal.ts
> +        <div class='row'>
Usually, we use `"` instead of `'` in html.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Auth/AuthModal.ts
> + * @param event Clicking on btn.
PLease do not reduce in the comments, it should be better `... on button`

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Auth/AuthModal.ts
> +  M.Modal.init(TEMPLATE_EL);
`M` is not obvious.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Navbar/Navbar.ts
> +  <nav class="blue-grey lighten-1">
Need to format HTML, missed nesting.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Navbar/Navbar.ts
> +LOGIN_LI_EL.innerHTML = `<a href="#modal-auth" class="modal-trigger">Login</a>`;
Looks like it should be a `button` instead of `a`.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Navbar/Navbar.ts
> +REG_LI_EL.innerHTML = `<a href="#modal-auth" class="modal-trigger">Register</a>`;
The same with `a`.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Table/Pagination.ts
> +<li class="disabled btn_prev"><a><i class="material-icons">chevron_left</i></a></li>
PLease format templates.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Table/Pagination.ts
> +let current_page = 1;
Why kebab_case?

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Table/Pagination.ts
> +function numPages(): number {
Functions should call starting with a verb. Ex: `getUser` `setUser`, `removeUser`, ... In this case, it should be like `getNumberPages`.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/components/Table/Table.ts
> +export const table = (): HTMLTableElement => {
Not clear what is table function, need a more informative name.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/detail/index.html
> +
Empty row, please remove it.

2022-02-15 04:23 UTC, golovachev-yaroslav commented on vanila/src/detail/index.html
> +      <a class="waves-effect waves-light  blue-grey lighten-1 btn">Edit</a>
`a` without `href` without is does not make sanse.

2022-02-15 04:38 UTC, panov-aleksey-saritasa requested changes

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/package.json
> +    "@types/jquery": "^3.5.13",
Do you need this? I don't see you using `jquery` anywhere

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/Navbar/Navbar.ts
> +  </nav>`;
Fix indentation for html template, please :)

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/Navbar/Navbar.ts
> +LOG_OUT.innerHTML = `<a href="" class="modal-trigger">Logout</a>`;
Please, avoid [contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions). `LOGIN_LI_EL` and `REG_LI_EL` are not very readable names, are they?

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/SearchAndSortSection/SearchSpace.ts
> +import { selectSort } from './SelectSort';
Remove comment

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/SearchAndSortSection/Search.ts
> +};
Tbh, I am not getting idea why need to make `getElement` function to return `SEARCH_ELEMENT`. Why can't you just return `SEARCH_ELEMENT` right away? Could you clarify it, please?

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/SearchAndSortSection/Search.ts
> +
Missing `JSDoc`. It's a function too, right? You could add `eslint` rule about `JSDoc` for arrow functions too or use `function declaration` syntax instead

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/Table/Pagination.css
> +.pages.pages{
Strange selector. If it's intended hack, please, write a comment of find a better solution

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/SearchAndSortSection/SelectSort.ts
> +   * Materialize css is so dumb, and you need to use setTimeout to avoid error.
🥲

2022-02-15 04:38 UTC, panov-aleksey-saritasa commented on vanila/src/components/Table/Pagination.ts
> +    const btnPrev = <HTMLLIElement>PAGINATION_ELEMENT.querySelector('.btn_prev');
Again about [contactions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-15 04:46 UTC, panov-aleksey-saritasa commented on vanila/src/components/Table/Pagination.ts
> +function numPages(): number {
[wiki](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#ahclc-pattern)

2022-02-15 04:49 UTC, Danissimo-k commented on vanila/src/components/Auth/AuthModal.ts
> +  M.Modal.init(TEMPLATE_EL);
M is global var from materialize css. Should I comment explanation for this step?

2022-02-15 04:50 UTC, golovachev-yaroslav commented on vanila/src/components/Auth/AuthModal.ts
> +  M.Modal.init(TEMPLATE_EL);
Yes, please.

2022-02-15 04:53 UTC, Danissimo-k commented on vanila/src/components/Navbar/Navbar.ts
> +LOGIN_LI_EL.innerHTML = `<a href="#modal-auth" class="modal-trigger">Login</a>`;
It is materialize css button. 
https://materializecss.com/navbar.html

2022-02-15 04:53 UTC, Danissimo-k commented on vanila/src/components/Navbar/Navbar.ts
> +REG_LI_EL.innerHTML = `<a href="#modal-auth" class="modal-trigger">Register</a>`;
It is materialize css button.
https://materializecss.com/navbar.html

2022-02-15 05:03 UTC, timofei-maximov-saritasa commented on vanila/src/detail/index.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"
You don't need it here, since you have installed it via npm.

2022-02-15 05:03 UTC, timofei-maximov-saritasa commented on vanila/src/firestore/firestoreOperations.ts
> + * ields to sort by.
Please, check formatting.

2022-02-15 10:29 UTC, elena-dragunova approved these changes

2022-02-15 10:29 UTC, elena-dragunova commented on vanila/src/detail/index.html
> +    <h2>Film</h2>
I suppose it shoud be h1

2022-02-15 11:45 UTC, dbitkovski requested changes

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/SearchAndSortSection/SelectSort.ts
> +   * Materialize css is so dumb, and you need to use setTimeout to avoid error.
When you use a workaround, please, provide a link to an issue you solve or, if there is no GitHub issue, add a good description _(and probably create an issue in library repo to help other developers)_
Your comment does not say a lot about the problem.

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/SearchAndSortSection/SelectSort.ts
> +      SELECT_DIV_ELEMENT.addEventListener('change', event => sortTable((<HTMLTextAreaElement>event.target).value));
Why your function is called `initStyles` but you add an event listener that sorts a table? Doesn't it look odd for you?

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/Pagination.ts
> +              });
formatting issues

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/Table.ts
> +export function setFilmsInTable(filmsDocs: CollectionDocument<FilmDTO>[]): void {
Again, don't work with dto in domain layer

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/Pagination.ts
> +import { FilmDTO } from '../../DTO/filmDTO';
Why does the component import DTO model? I think you need to map dto to domain models and then work only with it in your UI layer

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/Table.ts
> +let isAuthedTable = false;
a table cannot be authorized, please, come up with a better name

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/Table.ts
> +    });
Useless catch operator. You don't handle an error, just throw it away

2022-02-15 11:45 UTC, dbitkovski commented on vanila/src/components/Table/TableArea.ts
> +export const tableArea = (): HTMLDivElement => TABLE_AREA_EL;
missing doc

2022-02-16 05:04 UTC, timofei-maximov-saritasa requested changes

2022-02-16 05:04 UTC, timofei-maximov-saritasa commented on vanila/src/middlewares/getFormattedCollectionDataWithId.ts
> +  }
It looks almost identical to [getFormattedCollectionData](vanila/src/middlewares/getFormattedCollectionData.ts)

2022-02-16 06:41 UTC, viktor-sakhno-saritasa commented on vanila/src/components/Table/Pagination.ts
> +
Remove empty line, please

2022-02-16 06:41 UTC, viktor-sakhno-saritasa commented on vanila/src/components/Table/Pagination.ts
> +
The same as above

2022-02-16 06:41 UTC, viktor-sakhno-saritasa commented on vanila/src/components/Table/Pagination.ts
> +    for (let i = (selectedPage - 1) * records_per_page; i < (selectedPage * records_per_page); i++) {
I think you can take the calculations out of the loop. Imagine if you had a resource-intensive calculation in a function that would be called on each iteration of the loop.

```suggestion
    const offset = (selectedPage * records_per_page);
    for (let i = (selectedPage - 1) * records_per_page; i < offset; i++) {
```

2022-02-16 06:41 UTC, viktor-sakhno-saritasa commented on vanila/src/components/Table/Pagination.ts
> +  for (let i = 0; i < getNumPages(); i++) {
The same as above. It would be better if you take the function out of the loop

2022-02-16 06:41 UTC, viktor-sakhno-saritasa commented on vanila/src/components/Table/Table.ts
> +      const { director, release_date, producer, title } = dataDTO.fields;
The component does not need to know about the DTO layer. Before using, you should map everything into a domain model.

2022-02-18 08:02 UTC, chernodub commented on vanila/src/components/Auth/AuthModal.ts
> +export const authModal = (): HTMLDivElement => {
Your function should either be a _verb_ or postfixed with _factory_, this is our [naming guidestyle](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#naming-functions)

2022-02-18 08:03 UTC, chernodub commented on vanila/src/components/Navbar/Navbar.ts
> +logOutElement.innerHTML = `<a href="" class="modal-trigger">Logout</a>`;
I think it would be a good idea to create a simple function for creating a list item in order to avoid so much duplication

2022-02-18 08:07 UTC, chernodub commented on vanila/src/components/SearchAndSortSection/Search.css
> +  margin-top: 1.05rem ;
Formatting issue, pls use Prettier or some other auto-formatter for your CSS

2022-02-18 08:11 UTC, chernodub commented on vanila/src/components/SearchAndSortSection/SearchSpace.ts
> +function initSpace(): void {
So, it's not really a space after all, right? Since it contains both the sort-selector and a search input? I recommend you to look for a better name

2022-02-18 08:30 UTC, golovachev-yaroslav approved these changes

2022-06-24 07:58 UTC, closed without merging