#jc19 258 angular table
saritasa-nest/camp-js-2022-daniil-koh pull request #3
Opened 2022-03-01 02:18 UTC by Danissimo-k

Add table, pagination, sorting, searching by title, init db.

2022-03-01 03:31 UTC, pavel-romanov8 requested changes

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/models/film.model.ts
> +  readonly created: string;
Use the `Date` object for dates instead of plain strings in your models

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/mappers/film.mapper.ts
> +      ...dto.fields,
Avoid such things and explicitly map each field from the dto to the model. It is very helpful if we face changes in our model of dto and we can see what **exactly** we should change in mapper

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +
Remove empty line

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  public constructor() { }
Remove empty constructor

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/shared/components/table/table.component.css
> +  font-size: 14px;
Please, prefer rems or ems for font-size. It will make your site more accessible for people that want to change their base font size in a browser

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/services/database.service.ts
> +export class Database {
It is **not** a database. The database is something that we are trying to abstract from our codebase + the file itself placed in the `service` folder, let's call it appropriately - `firestore.service.ts`. That way we are making it clear for the service clients that it is: 1 - service; 2 - specific service that works with the firestore.

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/services/database.service.ts
> +  public constructor(private firestore: AngularFirestore, private filmMapper: FilmMapper) {
Declare service dependencies as read-only

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/services/database.service.ts
> +  public lastVisibleDocPaginator: QueryDocumentSnapshot<FilmDTO> | null = null;
Are you sure it is a good idea to make a mutable reference that can be accessed from any component that provides the service? Please, improve your approach so the data can't be mutated from the outside. You can use observables and subjects for it. If you have any questions feel free to contact with me

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/services/database.service.ts
> +  public getNextPage = (limitFilms: number, sortField: string, sortKey: 'desc' | 'asc', searchString: string): Observable<FilmModel[]> => {
Move the `sortKey` type into a standalone type:
```
type SortDirection = 'desc | asc'
```
That way you always have 1 source of truth for all methods in the service

2022-03-01 03:31 UTC, pavel-romanov8 commented on angular/src/app/core/services/database.service.ts
> +export class Database {
And as i see this service primarily works with films. It would be better to separate it into 2 different services - `firestore.service` where you can handle all logic that related to firestore independent from a collection you are working with and the film service that is using the firestore service to get info specifically about films

2022-03-01 04:18 UTC, kristinaSvobodinaSaritasa requested changes

2022-03-01 04:18 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/services/database.service.ts
> +  public getData = (pathCollection: string): Observable<FilmModel[]> => {
It seems strange that function has param pathCollection, but return always Film.

2022-03-01 04:18 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/services/database.service.ts
> +    }
Functions `getFilms`, `getNextPage` and `getPreviousPage` have a lot of repetitive code, I think you can improve you code, to avoid copy-past code.

2022-03-01 04:18 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/shared/components/table/table.component.ts
> +        this.data = data;
Try to rewrite without subscription, return data$ as Observable, and using async pipe. If you have questions, you could write me for helping.

2022-03-01 10:24 UTC, chernodub requested changes

2022-03-01 10:24 UTC, chernodub commented on angular/src/app/core/services/database.service.ts
> +                            sortKey: 'desc' | 'asc', searchString: string): Observable<FilmModel[]> => {
We don't format it like that in JS. Here's our way:
```
  function getPreviousPage(
    limitFilms: number, 
    sortField: string,
    sortKey: 'desc' | 'asc', 
    searchString: string,
  ): Observable<FilmModel[]> {...}
```

2022-03-01 10:24 UTC, chernodub commented on angular/src/app/core/services/database.service.ts
> +   * Get next page of films.
Wrong jsdoc

2022-03-01 10:24 UTC, chernodub commented on angular/src/app/core/services/database.service.ts
> +    // It need to make pagination, we should reverse sort key to take pre
It's not clear what `to take pre` means :(

2022-03-01 10:24 UTC, chernodub commented on angular/src/app/core/services/database.service.ts
> +    if (sortKey === 'asc') {
You could use a ternary operator to make it clearer/shorter and to make it a constant

2022-03-01 13:40 UTC, dbitkovski requested changes

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/app.module.ts
> +import { environment } from '../environments/environment.prod';
I think you need to import the object from the `environment` file. Angular will replace this file with `environment.prod` when you build in production mode. We never use it directly.

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/navbar/navbar.component.html
> +    aria-label="Example icon-button with menu icon"
Don't forget about `type` attribute

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  <div *ngIf="this.isAuth; else notAuthed">
When you use class properties on a template you don't need to specify `this`. Your template is bound to a specific class so it can access only properties of this class and angular allows you to write like this: `*ngIf="isAuth"`

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/navbar/navbar.component.html
> +      aria-label="Example icon-button with heart icon"
same about `type` attribute

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.html
> +      aria-describedby="Show films from db."
When you leave comments for app users try to imagine that you are a common user. Do you feel okay if you see such a message? Do you really need to know that these films are from somewhat that called *db*?

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.html
> +    aria-label="Select page of GitHub search results"
Update the text :)

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.ts
> +    const inputChange$ = fromEvent<InputEvent>(this.input.nativeElement, 'keyup')
That's not a bad approach but honestly, I'd replace it with a simple function that's triggered on `ngModelChange`.
Here is a small example:
```
<input [ngModel]="filterInputValue" (ngModelChange)="onSearchInputChanged()">

onSearchInputChanged() {
  ... // this.filterInputValue already has a new value here
}
```

2022-03-01 13:40 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.ts
> +        this.data = data;
Kristina is totally right. More often using `detectChanges` means you're doing something wrong. In case you need to show async data on UI `async` pipe is the best solution.

2022-03-01 18:11 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/mappers/dto/vehicleDTO.ts
> +export interface VehicleDTO {
We prefer to name dto entities without capitalization only, for example: `VehicleDto` or `UserDto`.

2022-03-01 18:11 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/services/database.service.ts
> +   *  @param searchString String to search in data.
Formatting.

2022-03-01 18:11 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/table/table.component.ts
> +  @ViewChild(MatSort) private sort!: MatSort;
We prefer to write decorator and property on different lines.

```suggestion
  @ViewChild(MatSort) 
  private sort!: MatSort;
```

2022-03-02 09:56 UTC, Danissimo-k commented on angular/src/app/core/services/database.service.ts
> +  public lastVisibleDocPaginator: QueryDocumentSnapshot<FilmDTO> | null = null;
@pavel-romanov8 Can I just make private variable to encapsulate my data?

2022-03-02 12:37 UTC, Danissimo-k commented on angular/src/app/core/mappers/dto/filmDTO.ts
> +  readonly characters: ReadonlyArray<number>;
I am sure that he told about _ReadonlyArray_.

2022-03-02 12:43 UTC, Danissimo-k commented on angular/src/app/core/mappers/dto/collectionDTO.ts
> +   *Model of item.
@chernodub, @pavel-romanov8 said to use inline comment, as i understand.
> Please, replace with accurate docstring

2022-03-02 12:43 UTC, Danissimo-k commented on angular/src/app/core/mappers/dto/collectionDTO.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
@chernodub, @pavel-romanov8 said to use inline comment, as i understand.
> Please, replace with accurate docstring

2022-03-02 14:46 UTC, timofei-maximov-saritasa requested changes

2022-03-02 14:46 UTC, timofei-maximov-saritasa commented on angular/src/app/core/mappers/dto/speciesDTO.ts
> +  readonly skin_colors: string;
Your doc string doesn't match with property. As I can see, that there should be many skin colors from your property name. And, if I'm not mistaken, `species` have `skin_color` property but it is a comma separated values.

2022-03-02 14:46 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/table/table.component.css
> +}
Please, be consistent with css selectors. If you need this style only for your film table, then use class selector. Or if you want this style for all your possible tables, then move it to global styles.

2022-03-02 14:46 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/table/table.component.ts
> +  public data!: FilmModel[];
Perhaps, we can come up with better name?

2022-03-03 05:41 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +    const inputChange$ = fromEvent<InputEvent>(this.input.nativeElement, 'keyup')
So but I do not know how make it as abservable, If you know it, could you please to hemp me with this issue?

2022-03-03 06:26 UTC, Danissimo-k commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  <span class="example-spacer"></span>
I don't have any idea how to float my buttons to right. Itried use `float` but it didnt work. Coul you give me an idea how I can realize it, please?

2022-03-03 07:51 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  <span class="example-spacer"></span>
@Danissimo-k https://codepen.io/Moltenship/pen/dyZwjbE

2022-03-04 09:20 UTC, elena-dragunova approved these changes

2022-03-04 09:20 UTC, elena-dragunova commented on angular/src/app/core/mappers/dto/character.dto.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention
For dto files you can use '/* eslint-disable @typescript-eslint/naming-convention */' just once - in the beginning of the file.

2022-03-04 15:40 UTC, Danissimo-k commented on angular/src/app/core/mappers/dto/character.dto.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention
@elena-dragunova So you offer the third variant of this situation. :D 
I had you variant in before my commits, but @pavel-romanov8  said use inline disablers and @chernodub offer to use special file. So funnny situation. I do not know what to do.

2022-03-05 06:33 UTC, pavel-romanov8 requested changes

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/mappers/dto/character.dto.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention
@Danissimo-k I don't remember that I said such things

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +export class TableFilms {
We should not bring any ui related terms and parts to domain / repository layer. Service shouldn't be named `like `TableFilms` it is `FilmsService`

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> + * Service that provide films for table.
The same thing about ui mix into domain

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +  public getSortedDataByKey(pathCollection: string,
The method name sounds more like generic one, but in fact you are getting **films** not just random **data**

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +   * Get data with reference from database.
You are writing about data, but in fact getting films. Please, provide more precise documentation.

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +   * Get data with reference from database.
And as I mentioned in previous comments, we shouldn't operate terms like 'database' 'server' and so on the domain layer, because it is abstraction over them

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +    let films$ = collectionRef.snapshotChanges().pipe(
There is no need to create the variable, you can return the `snapshotChanges` right away

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +    if (shouldReverse) {
You can move it to the pipe chain operators:
```ts
map(films => shouldReverse ? films.reverse() : films)
```

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/navbar/navbar.component.css
> +.auth-buttons{
Please, format your CSS files properly

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +export interface TableFilmsParameters{
```suggestion
export interface TableFilmsParameters {
```

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/core/services/table-films.ts
> +    const defaultSortField = 'title';
You are duplicating the same constants over methods in the service, please, move them to upper scope

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +  public constructor(private readonly database: TableFilms) {
Please, rename the variable, that hold reverence to the service. We shouldn't operate terms like `database` on the UI layer

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +  public films$!: Observable<Film[]>;
There is no need to initialize the variable in `afterViewInit`. You can do it in the constructor

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +    this.sort.sortChange.subscribe(() => {
Please, handle your subscriptions properly, because for now you have a memory leak. You can use `takeUntil` and subject or use the `async` pipe

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +    /** Server-side search. */
As i already mentioned, we should bring such terms on the UI

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +   * Reference on input, field.
When we write `inheritDoc` that means there is no need to provide additional info for the field, and we leave it as is. Please, either leave `inheritDoc` or the comment.

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +  @ViewChild('input') private input!: ElementRef<HTMLInputElement>;
Place such decorators and their field on separate lines:
```suggestion
  @ViewChild('input')
  private input!: ElementRef<HTMLInputElement>;
```

2022-03-05 06:33 UTC, pavel-romanov8 commented on angular/src/app/shared/components/home/table/table.component.ts
> +   * Reference on sort table.
Please such docs **above** the decorator

2022-03-09 02:23 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.ts
> +    const inputChange$ = fromEvent<InputEvent>(this.input.nativeElement, 'keyup')
Make the `inputChange$` property a subject and push value into it within `onSearchInputChanged`

2022-03-16 05:39 UTC, chernodub commented on angular/src/app/core/services/database.service.ts
> +  public lastVisibleDocPaginator: QueryDocumentSnapshot<FilmDTO> | null = null;
Yes that would be ok @Danissimo-k

2022-03-16 05:40 UTC, chernodub commented on angular/src/app/core/mappers/dto/collectionDTO.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
He mean to fix your JSDoc that describes a property, not to use inline disabling of eslint rules :)

2022-03-16 05:43 UTC, chernodub commented on angular/src/app/core/mappers/dto/character.dto.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention
@Danissimo-k https://github.com/saritasa-nest/camp-js-2022-daniil-koh/pull/3#discussion_r827644926

@Danissimo-k please try to avoid the inline disabling of eslint at all times. In case when you need to disable a rule for a directory of files, you create a local `.eslintrc` file, where you override the rule. For more information, you could either ask your peers or contact me directly in Slack

2022-03-16 06:16 UTC, chernodub requested changes

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/home.module.ts
> +export class HomeModule {
So, this is a full-fledged feature, right? It's very weird that you decided to put it in a `components` folder, consider revising your directory tree structure

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/navbar/navbar.component.html
> +  <div *ngIf="isAuth; else notAuthed" class="auth-buttons">
There is no word `authed`, `authorized` is the one you want. Please check your grammar, you could use a spellchecker extension 🙂

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/navbar/navbar.component.html
> +    <div class="auth-buttons">
Please stick to BEM naming

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.html
> +      aria-label="StarWars films."
Consider using `<caption>` instead

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +        .orderBy(`fields.${sortField}`, sortKey)
But your domain property names are different from the ones used in DTOs, right? Therefore, this sorting won't work in cases where your domain name is different. Please add some sort of mapping here

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.html
> +        <td mat-cell *matCellDef="let row">{{ row.title }}</td>
Consider using `mat-text-column` for simple text fields, this will make your markdown more readable

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.ts
> +import { FilmDto } from '../../../../core/mappers/dto/film.dto';
Your ui layer, should **never** know anything about DTO, please check out our [architecture section](https://frontendwiki.saritasa.rocks/pages/development/angular/architecture.html)

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.ts
> +
@Danissimo-k I don't see Pavel's comment resolved, please never mark it resolved before you fix it. If you do not agree, leave a comment and make sure the commenter saw this and approved your point

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.ts
> +  private resetPagination = (): void => {
What's the point using arrow function in the context of a class? Consider using function declaration isntead, this is our future styleguide, you can check our [discussion on the topic](https://github.com/saritasa-nest/saritasa-frontend-wiki/pull/35/files#r811178789)

2022-03-16 06:16 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.ts
> +    this.sort.active = 'title';
Since you mutate an object property, the change detection (with OnPush enabled) may not work as expected, please be careful

2022-03-19 14:22 UTC, Danissimo-k commented on angular/src/app/core/models/film.ts
> +   * String of producers(separated by ",") or producer.
@chernodub I can't see my mistake, could you please emphasise it?

2022-03-19 14:32 UTC, Danissimo-k commented on angular/src/app/core/services/films.service.ts
> +  private firstVisibleDocPaginator: QueryDocumentSnapshot<FilmDto> | null = null;
@chernodub The paginator needs a cursor to paginate data, I think. I believe the cursor is the document we use to paginate movies and the paginator is already paginating them.

2022-03-19 16:07 UTC, Danissimo-k commented on angular/src/app/core/services/films.service.ts
> +        .orderBy(`fields.${sortField}`, sortKey)
@chernodub So, I have some problems with mapped types. Can I call you and get piece of advice?

2022-03-21 03:15 UTC, timofei-maximov-saritasa requested changes

2022-03-21 03:15 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/table/table.component.html
> +    </div>
This looks really weird. Can't you just use loading, since `mat-spinner` will be visible only if loading is `true`

2022-03-21 03:15 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/table/table.component.ts
> +    });
Do not forget to unsubscribe from your subscriptions

2022-03-21 04:34 UTC, thanhnguyen-saritasa commented on angular/src/app/shared/components/table/table.component.ts
> +  public pageSize = 2;
Could you please help me understand why is it initialized with value "2"

2022-03-22 12:02 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +  public pageSize = 2;
@thanhnguyen-saritasa Yeah, we have only 6 films in our database and our teamlead said that 2 films in one page are enough for camp project.

2022-03-22 15:00 UTC, Danissimo-k commented on angular/src/app/shared/components/home/table/table.component.html
> +        <td mat-cell *matCellDef="let row">{{ row.title }}</td>
@chernodub I have problem with it, all fields render good, except date type. I tried to transform date to type via `dateAccessor`, but it didnt help.

2022-03-24 09:34 UTC, dbitkovski commented
@Danissimo-k sorry that we noticed it too late, but "_Pull request fixes_" is a pretty bad commit message :(
Sometimes it's difficult to come up with a good name for all files. In such situation consider making several small commits but with a understandable messages

2022-03-24 10:08 UTC, dbitkovski commented on angular/src/app/shared/components/table/table.component.ts
> +  public films$!: Observable<Film[]>;
Don't forget about `readonly` and please, don't use non-null assertion operator, it's not safe at all. If your class property is not initialized during the contructor, use according types.

2022-03-24 10:08 UTC, dbitkovski commented on angular/src/app/shared/pipes/date-formatter.pipe.ts
> +    if (!isNaN(date.getTime())) {
Good catch, I didn't know that angular `Date` pipe does not handle such cases

2022-03-25 04:06 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.html
> +      }}
Ohhh. Let's forget about it.

2022-03-25 04:12 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +  public films$!: Observable<Film[]>;
@dbitkovski I actually cant readonly, cause I init my films in `ngAfterViewInit`.

2022-03-25 04:15 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +  public films$!: Observable<Film[]>;
I tried to transpot it in cinstructor, but `input` is not rendered when I tried to init `films$`, if you have a good idea, please could you help to resolve this task?

2022-03-29 01:03 UTC, chernodub commented on angular/src/app/core/models/film.ts
> +   * String of producers(separated by ",") or producer.
@Danissimo-k this is an array of producers, not a string separated by `,` :)

2022-03-29 01:03 UTC, chernodub commented on angular/src/app/shared/components/home/table/table.component.html
> +        <td mat-cell *matCellDef="let row">{{ row.title }}</td>
For date, you could use a regular `th/td` approach

2022-03-29 02:56 UTC, chernodub requested changes

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +  private firstVisibleDocPaginator: QueryDocumentSnapshot<FilmDto> | null = null;
In docs, you specified that it's a cursor, but in the name it's a paginator. That's what I meant, make it consistent :)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +   * Getting films from firestore for table.
Your domain service should never expose internal repository information. Please check out our [architecture section](https://frontendwiki.saritasa.rocks/development/angular/architecture)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +    // Get reverses data because we reverse earlier.
Pls check your grammar here :)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +          if (data.length < limitData) {
Isn't `data.length` going to be equal to `limitData`, in case it's enough items to populate the page? This way, you could reduce this expression to `const lastDocIdx = data.length - 1`.

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +      } as FilmWithId))),
Consider mapping it inline, no need to create `{id, data}`

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +        .orderBy(`fields.${this.fieldDtoMapper[sortField]}`, sortKey));
Shouldn't you limit films here?

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/navbar/navbar.component.html
> +    <button mat-icon-button class="logout-icon" type="button">
https://frontendwiki.saritasa.rocks/development/languages/html#title-for-controlslinks-that-do-not-contain-representative-text

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +// TODO Connect auth state Subscriber Template with Rx.
Is this going to be implemented ? :)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.css
> +.loading-shade {
[Please stick to BEM](https://frontendwiki.saritasa.rocks/development/languages/css#bem)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +    <!-- Table -->
This seems like a useless comment, we already see `table` tag :)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +      <mat-spinner *ngIf="isLoadingResults"></mat-spinner>
Are you sure you need two `ngIf` in this case?

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +      }}
@Danissimo-k please explain :)

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +          {{ row.created | dateFormatter }}
Usually, when we create a pipe that's domain specific, we give it a prefixed name like `swDate`. No need to add obvious suffixes like `Formatter`

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +  @ViewChild('input', { static: false })
1. It's `static: false` by default, no need to make it explicit
2. You can make it `static: true` when it's not wrapped with structural directives. This way you can access it on earlier lifecycle callbacks, particularly `ngOnInit`

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +    this.paginator.pageIndex = 0;
Should you reset the pagination in the service too? Since it's stateful

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +  private changeFieldSortToDefault = (): void => {
What's the point making it an arrow function?

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +        (click)="goToDetailPage(row.id)"
Please prefer `routerLink` (and `a` tag) for navigation

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +        debounceTime(1000),
Consider moving the hardcoded number to a named constant

2022-03-29 02:56 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +        this.input.nativeElement.value = '';
Please do not manipulate HTML elements directly. Angular provides convenient abstractions over it. Forms API could be used here

2022-03-29 11:15 UTC, Danissimo-k commented on angular/src/app/core/services/films.service.ts
> +  private readonly defaultSortField: string = 'title';
@chernodub Sry, I don't understand you. Should I change `string ` type to `keyof Film` ?

2022-03-29 12:08 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +    const inputChange$ = fromEvent<InputEvent>(this.input.nativeElement, 'keyup')
@dbitkovski I have tried to replace it but i got problem. When I tried to replace it by a subhect and remove my `private input!: ElementRef<HTMLInputElement>;` I need event `keyup` to listen changes. If I try to listen suubject and subscrive to it, my app will fetch each time when I try to next value into subject, it makes so match problem.

2022-03-29 12:27 UTC, Danissimo-k commented on angular/src/app/core/services/films.service.ts
> +          if (data.length < limitData) {
@chernodub No, in my first fetch I need to fetch all films and get length from them to paginate it well.

2022-03-29 13:51 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.html
> +    <!-- Table -->
:c

2022-03-29 13:55 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.html
> +      }}
@chernodub I was young and stupid

2022-03-29 14:13 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +    this.paginator.pageIndex = 0;
@chernodub Service doesnt store pagination, it only stores cursors. (I know that storing cursors in a service is wrong :c)

2022-03-29 15:18 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.html
> +        (click)="goToDetailPage(row.id)"
@chernodub I do not have idea how to insert a tag `<a>` into row. Could you please give me a piece of advice?

2022-03-29 15:42 UTC, Danissimo-k commented on angular/src/app/shared/components/table/table.component.ts
> +        this.input.nativeElement.value = '';
@chernodub Yeah, I knew it, but I can't add event listener on `FormControl`, and I cant get native element from `FormControl`

2022-03-31 05:51 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +  private readonly defaultSortField: string = 'title';
I mean that you should move `defaultSortField` from the class to `const DEFAULT_SORT_FIELD` outside of the class in order to make it's interface simpler

2022-03-31 05:52 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.html
> +        (click)="goToDetailPage(row.id)"
Usually, for this we put `a` in each `td`. Yeah, it's inconvenient, but it's semantically correct

2022-03-31 05:53 UTC, chernodub commented on angular/src/app/shared/components/table/table.component.ts
> +        this.input.nativeElement.value = '';
You don't need an event listener when using form controls. You have `valueChanges` property and other stuff for handling user-based events

2022-04-06 01:15 UTC, closed without merging