Feature/#jc19 299 films table & auth
saritasa-nest/camp-js-2022-daniil-koh pull request #4
Opened 2022-03-29 10:13 UTC by Danissimo-k

Realize films table and authetication

2022-03-29 10:35 UTC, golovachev-yaroslav requested changes

2022-03-29 10:35 UTC, golovachev-yaroslav commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +          onClick={() => signUpWithGoogleHandler()}
Didn't pass params, therefore you can reduce `onClick={signUpWithGoogleHandler}`

2022-03-29 10:35 UTC, golovachev-yaroslav commented on react/src/features/common/components/Navbar/Navbar.tsx
> +import { useAppDispatch, useAppSelector } from '../../../../store';
You can setup relative paths for your components. 
Something like this:
`import { useAppDispatch, useAppSelector } from 'src/store';`
https://stackoverflow.com/questions/43281741/how-to-use-paths-in-tsconfig-json

2022-03-29 10:35 UTC, golovachev-yaroslav commented on react/src/features/films/components/table/FilmsTable.tsx
> +            <TableRow
Missed key 
https://reactjs.org/docs/lists-and-keys.html#keys

2022-03-29 10:35 UTC, golovachev-yaroslav commented on react/src/features/films/components/table/Table.css
> +/*.films-table-body {*/
Please remove if you don't use this code.

2022-03-29 10:35 UTC, golovachev-yaroslav commented on react/src/features/films/components/textFieldFilm/TextFieldFilm.tsx
> +      onChange={event => inputChangesHandler(event)}
You can reduce the code
`onChange={inputChangesHandler}`

2022-03-29 13:40 UTC, timofei-maximov-saritasa requested changes

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/api/models/species.ts
> +  readonly people: readonly string[];
If it's an array with primary keys, then you should rename the field

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/api/services/auth.service.ts
> +        resolve(!!user);
[Don't use implicit type-casting](https://frontendwiki.saritasa.rocks/development/languages/typescript#dont-use-implicit-type-casting)

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +          onClick={() => signUpWithGoogleHandler()}
As we discussed at lecture, you can use `useCallback` hook to optimize your renders. [React docs](https://reactjs.org/docs/hooks-reference.html#usecallback)

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/features/common/components/Navbar/Navbar.tsx
> +export default Navbar;
We prefer using named exports over default exports. You can read the reasons [here](https://jakearchibald.com/2021/export-default-thing-vs-thing-as-default/)

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/store/films/slice.ts
> +    searchStringChange: (state, { payload }) => {
I guess, it should be named like: `setSearchString`.

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/store/films/slice.ts
> +    searchStringChange: (state, { payload }) => {
And do you really need it in your store?

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/store/films/slice.ts
> +      state.films = castDraft(action.payload.films);
[Your data should be normilized](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape). Redux toolkit [provides awesome tool](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape) for helping you with it.

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  const [films, setFilms] = useState<FilmWithId[]>([]);
Do you really need it? Since you have redux and selectors?

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/store/user/state.ts
> +}
Your loading is missing :(

2022-03-29 13:40 UTC, timofei-maximov-saritasa commented on react/src/routes/guards/auth.guard.tsx
> +  needAuth?: boolean;
Missing readonly

2022-03-30 02:25 UTC, Danissimo-k commented on react/src/features/common/components/Navbar/Navbar.tsx
> +import { useAppDispatch, useAppSelector } from '../../../../store';
@golovachev-yaroslav Hmm, I tried to use it, but React throw error `Module not found: Error: Can't resolve '@store'`. But Ide say nothing about that.

2022-03-30 06:19 UTC, Danissimo-k commented on react/src/features/films/components/table/FilmsTable.tsx
> +  const [films, setFilms] = useState<FilmWithId[]>([]);
Yeah, in redux I store fetched films, in this I store films which are located in table, I cant store all films in redux, cause i have elements with the same ids.

2022-03-30 06:20 UTC, Danissimo-k commented on react/src/store/user/state.ts
> +}
:0

2022-03-30 06:30 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  const [films, setFilms] = useState<FilmWithId[]>([]);
Still, I don't see a reason do this. Please, remove it. You can manage it with redux. Once again, if you normilize your store, it will be easier to solve

2022-03-30 16:22 UTC, timofei-maximov-saritasa commented on react/src/api/models/character.ts
> +  readonly edited: Date;
I think, you can omit fields that you are not going to use

2022-03-30 16:24 UTC, timofei-maximov-saritasa commented on react/src/api/models/film-details.ts
> +  readonly characters: DocumentDataWithId<Character>[];
Missing readonly for arrays

2022-03-30 16:25 UTC, timofei-maximov-saritasa commented on react/src/api/models/species.ts
> +  readonly eyeColors: string;
I think it should be an array

2022-03-30 16:32 UTC, timofei-maximov-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +import './AuthPage.css';
We use css modules in our projects. Usually we name it like `[ComponentName].module.css`. Then we import, and use as an object. You can find an example [here](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/#buttonjs).

2022-03-30 16:33 UTC, timofei-maximov-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +      <h3 className="auth-title">
[Please, use `Typography` component](https://mui.com/components/typography/).

2022-03-30 16:35 UTC, timofei-maximov-saritasa commented on react/src/features/common/components/Navbar/Navbar.tsx
> +                <Button
Add `type` attribute for buttons.

2022-03-30 16:36 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  sortDirection: FilmsService.SortDirection;
Missing readonly

2022-03-30 16:39 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  const sortedColumns = arrayOfAllShowedColumns(['title', 'producer', 'director', 'created']);
Do you really need table in your sidebar. I think, the task was to make a list of cards with infinite scroll support and film details on the right side. It is just weird to fit a table with 4 columns in sidebar. It is not the best UX solution.

2022-03-30 16:44 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  }, [searchStringFilms, sortState.sortDirection, sortState.sortedColumn]);
If I'm not mistaken, MUI provides `debounce` helper function

2022-03-30 16:46 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +            {loading && <CircularProgress className="films-loading" color="inherit" />}
I see, that you repeating your `CircularProgress` component with `color="inherit"`. Perhaps, it is better to create custom loader component to reduce code duplication?

2022-03-30 16:49 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/textFieldFilm/TextFieldFilm.tsx
> +  );
Do you really want to save your seach query in redux?

2022-03-30 16:55 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/textFieldFilm/TextFieldFilm.tsx
> +  );
Moreover, you components are connected with redux, you dispatch fetch action in table component, but why do you need search component to get search string? Won't it be easier to place it with filters?

2022-03-31 03:39 UTC, panov-aleksey-saritasa requested changes

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/models/user.ts
> +export type UserFireAuth = User;
Prefer always creating your own models so your UI layer wouldn't know anything about entities of external libraries like `firebase`

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/models/film-with-id.ts
> +}
Could you clarify why do you need `Film` without id? 🤨️

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/auth.service.ts
> +    return Boolean(user);
Please, [avoid implicit type casting](https://frontendwiki.saritasa.rocks/development/languages/typescript#dont-use-implicit-type-casting)

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +    | 'created';
I think `columns` is a bad name here, since it's UI related thing

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +  export type PageDirection = 'previous' | 'next';
I think sort direction and page direction are rather general and reusable models, you shouldn't put them in `FilmsService`

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +  };
You could make it like this: `Record<keyof SortedColumns, string>`

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +  };
As I see, it's not mapper for dto fields, but rather mapper for sorted columns

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +      .then(films => (shouldReverse ? films.reverse() : films))
`reverse` mutates source array, [please avoid that](https://frontendwiki.saritasa.rocks/development/practices/code#promote-immutability)

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.css
> +  --auth-container-border-color:  rgba(40, 60, 80, 0.3);
Seems unused

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/features/common/components/Navbar/Navbar.tsx
> +          <div className="navbar-button">
I see you are using `Box` component in other places, then for consistency prefer using it over `div`

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  }, [searchStringFilms, sortState.sortDirection, sortState.sortedColumn]);
Or you can write your own `debounce` function, it's not that difficult :)

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +  const loading = useAppSelector(selectFilmsLoading);
Prefer adding `is`, `can`, `has` and etc. prefixes for boolean properties

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/features/films/components/table/FilmsTable.tsx
> +      setFilms([...fetchedFilmsData]);
```suggestion
      setFilms(fetchedFilmsData);
```

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/mappers/capitalizeFirstLetter.ts
> +}
Why it's in `mappers` folder? Isn't it just an util function?

2022-03-31 03:39 UTC, panov-aleksey-saritasa commented on react/src/models/arrayOfAll.ts
> +}
Why it's in `models` folder? Isn't it just an util function?

2022-03-31 03:46 UTC, panov-aleksey-saritasa commented on react/src/api/services/films.service.ts
> +      .then(films => (shouldReverse ? films.reverse() : films))
you can do it like this `[...films].reverse()` :)

2022-04-06 01:15 UTC, closed without merging